# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/projects/adv7511/zc702/system_constr.xdc

# XDC: imports/projects/common/zc702/zc702_system_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_clkgen_0/system_axi_hdmi_clkgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_clkgen_0 || ORIG_REF_NAME==system_axi_hdmi_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_core_0/system_axi_hdmi_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spdif_tx_core_0/system_axi_spdif_tx_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp0_interconnect_0/system_axi_hp0_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp0_interconnect_0 || ORIG_REF_NAME==system_axi_hp0_interconnect_0} -quiet] -quiet

# Block Designs: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/bd_a17c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_0/bd_a17c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_2/bd_a17c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_3/bd_a17c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_4/bd_a17c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/bd_a17c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/bd_a17c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_7/bd_a17c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_8/bd_a17c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_9/bd_a17c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_protocol_convert_0_0/system_axi_protocol_convert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_protocol_convert_0_0 || ORIG_REF_NAME==system_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/system/ip/system_vio_0_0/system_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vio_0_0 || ORIG_REF_NAME==system_vio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_0 || ORIG_REF_NAME==system_system_ila_0_0} -quiet] -quiet

# Block Designs: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8 || ORIG_REF_NAME==bd_d5b8} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/bd_d5b8_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_g_inst_0 || ORIG_REF_NAME==bd_d5b8_g_inst_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_2/bd_d5b8_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_0_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_0_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_3/bd_d5b8_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_0_w_0 || ORIG_REF_NAME==bd_d5b8_slot_0_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_4/bd_d5b8_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_0_b_0 || ORIG_REF_NAME==bd_d5b8_slot_0_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_5/bd_d5b8_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_0_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_0_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_6/bd_d5b8_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_0_r_0 || ORIG_REF_NAME==bd_d5b8_slot_0_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_7/bd_d5b8_slot_1_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_1_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_1_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_8/bd_d5b8_slot_1_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_1_w_0 || ORIG_REF_NAME==bd_d5b8_slot_1_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_9/bd_d5b8_slot_1_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_1_b_0 || ORIG_REF_NAME==bd_d5b8_slot_1_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_10/bd_d5b8_slot_1_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_1_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_1_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_11/bd_d5b8_slot_1_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_1_r_0 || ORIG_REF_NAME==bd_d5b8_slot_1_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_12/bd_d5b8_slot_2_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_2_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_2_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_13/bd_d5b8_slot_2_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_2_w_0 || ORIG_REF_NAME==bd_d5b8_slot_2_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_14/bd_d5b8_slot_2_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_2_b_0 || ORIG_REF_NAME==bd_d5b8_slot_2_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_15/bd_d5b8_slot_2_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_2_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_2_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_16/bd_d5b8_slot_2_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_2_r_0 || ORIG_REF_NAME==bd_d5b8_slot_2_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_17/bd_d5b8_slot_3_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_3_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_3_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_18/bd_d5b8_slot_3_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_3_w_0 || ORIG_REF_NAME==bd_d5b8_slot_3_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_19/bd_d5b8_slot_3_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_3_b_0 || ORIG_REF_NAME==bd_d5b8_slot_3_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_20/bd_d5b8_slot_3_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_3_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_3_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_21/bd_d5b8_slot_3_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_3_r_0 || ORIG_REF_NAME==bd_d5b8_slot_3_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_22/bd_d5b8_slot_4_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_4_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_4_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_23/bd_d5b8_slot_4_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_4_w_0 || ORIG_REF_NAME==bd_d5b8_slot_4_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_24/bd_d5b8_slot_4_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_4_b_0 || ORIG_REF_NAME==bd_d5b8_slot_4_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_25/bd_d5b8_slot_4_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_4_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_4_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_26/bd_d5b8_slot_4_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_4_r_0 || ORIG_REF_NAME==bd_d5b8_slot_4_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_27/bd_d5b8_slot_5_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_5_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_5_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_28/bd_d5b8_slot_5_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_5_w_0 || ORIG_REF_NAME==bd_d5b8_slot_5_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_29/bd_d5b8_slot_5_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_5_b_0 || ORIG_REF_NAME==bd_d5b8_slot_5_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_30/bd_d5b8_slot_5_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_5_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_5_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_31/bd_d5b8_slot_5_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_5_r_0 || ORIG_REF_NAME==bd_d5b8_slot_5_r_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_32/bd_d5b8_slot_6_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_6_aw_0 || ORIG_REF_NAME==bd_d5b8_slot_6_aw_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_33/bd_d5b8_slot_6_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_6_w_0 || ORIG_REF_NAME==bd_d5b8_slot_6_w_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_34/bd_d5b8_slot_6_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_6_b_0 || ORIG_REF_NAME==bd_d5b8_slot_6_b_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_35/bd_d5b8_slot_6_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_6_ar_0 || ORIG_REF_NAME==bd_d5b8_slot_6_ar_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_36/bd_d5b8_slot_6_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_slot_6_r_0 || ORIG_REF_NAME==bd_d5b8_slot_6_r_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_3_0/system_system_ila_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_3_0 || ORIG_REF_NAME==system_system_ila_3_0} -quiet] -quiet

# Block Designs: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/bd_d548.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d548 || ORIG_REF_NAME==bd_d548} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/bd_d548_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_1/bd_d548_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d548_g_inst_0 || ORIG_REF_NAME==bd_d548_g_inst_0} -quiet] -quiet

# IP: bd/system/ip/system_pow_0_0/system_pow_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pow_0_0 || ORIG_REF_NAME==system_pow_0_0} -quiet] -quiet

# IP: bd/system/ip/system_FFT_Top_0_1/system_FFT_Top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_FFT_Top_0_1 || ORIG_REF_NAME==system_FFT_Top_0_1} -quiet] -quiet

# IP: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_FFT_Top_0_1/src/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: bd/system/ip/system_axil_fw_0_0/system_axil_fw_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axil_fw_0_0 || ORIG_REF_NAME==system_axil_fw_0_0} -quiet] -quiet

# IP: bd/system/ip/system_procedural_0_3/system_procedural_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_procedural_0_3 || ORIG_REF_NAME==system_procedural_0_3} -quiet] -quiet

# IP: bd/system/ip/system_signal_gen_top_0_2/system_signal_gen_top_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_gen_top_0_2 || ORIG_REF_NAME==system_signal_gen_top_0_2} -quiet] -quiet

# IP: bd/system/ip/system_reg_map_fw_0_0/system_reg_map_fw_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_reg_map_fw_0_0 || ORIG_REF_NAME==system_reg_map_fw_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_0/system_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_regslice_0 || ORIG_REF_NAME==system_s00_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_data_fifo_0 || ORIG_REF_NAME==system_s00_data_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_m00_data_fifo_0/system_m00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_m00_data_fifo_0 || ORIG_REF_NAME==system_m00_data_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_0/system_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_rs_0/system_auto_rs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_rs_0 || ORIG_REF_NAME==system_auto_rs_0} -quiet] -quiet

# IP: bd/system/ip/system_m01_data_fifo_0/system_m01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_m01_data_fifo_0 || ORIG_REF_NAME==system_m01_data_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_1/system_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_1 || ORIG_REF_NAME==system_auto_ds_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_rs_1/system_auto_rs_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_rs_1 || ORIG_REF_NAME==system_auto_rs_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_2/system_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_2 || ORIG_REF_NAME==system_auto_ds_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_ds_3/system_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_ds_3 || ORIG_REF_NAME==system_auto_ds_3} -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_200m_rstgen_0/system_sys_200m_rstgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_200m_rstgen_0 || ORIG_REF_NAME==system_sys_200m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hdmi_core_0/axi_hdmi_tx_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_core_0 || ORIG_REF_NAME==system_axi_hdmi_core_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hdmi_dma_0/system_axi_hdmi_dma_0_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hdmi_dma_0 || ORIG_REF_NAME==system_axi_hdmi_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_audio_clkgen_0 || ORIG_REF_NAME==system_sys_audio_clkgen_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_sys_audio_clkgen_0/system_sys_audio_clkgen_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_spdif_tx_core_0/axi_spdif_tx_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_spdif_tx_core_0 || ORIG_REF_NAME==system_axi_spdif_tx_core_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_1/bd_a17c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_5/bd_a17c_s00a2s_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_6/bd_a17c_sarn_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_7/bd_a17c_srn_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/bd_0/ip/ip_8/bd_a17c_m00s2a_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_hp0_interconnect_0/ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axi_protocol_convert_0_0/system_axi_protocol_convert_0_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_vio_0_0/system_vio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vio_0_0 || ORIG_REF_NAME==system_vio_0_0} -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d548_ila_lib_0 || ORIG_REF_NAME==bd_d548_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/ip/ip_0/bd_d548_ila_lib_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_system_ila_3_0/bd_0/bd_d548_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_pow_0_0/src/timing.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_pow_0_0 || ORIG_REF_NAME==system_pow_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_FFT_Top_0_1/src/tim.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_FFT_Top_0_1 || ORIG_REF_NAME==system_FFT_Top_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_axil_fw_0_0/src/timing.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axil_fw_0_0 || ORIG_REF_NAME==system_axil_fw_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s00_regslice_0 || ORIG_REF_NAME==system_s00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s00_data_fifo_0 || ORIG_REF_NAME==system_s00_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_s00_data_fifo_0/system_s00_data_fifo_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_m00_data_fifo_0/system_m00_data_fifo_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m00_data_fifo_0 || ORIG_REF_NAME==system_m00_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_m00_data_fifo_0/system_m00_data_fifo_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_ds_0 || ORIG_REF_NAME==system_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_rs_0/system_auto_rs_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_rs_0 || ORIG_REF_NAME==system_auto_rs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_m01_data_fifo_0/system_m01_data_fifo_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m01_data_fifo_0 || ORIG_REF_NAME==system_m01_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_m01_data_fifo_0/system_m01_data_fifo_0_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_1/system_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_ds_1 || ORIG_REF_NAME==system_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_1/system_auto_ds_1_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_rs_1/system_auto_rs_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_rs_1 || ORIG_REF_NAME==system_auto_rs_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_ds_2 || ORIG_REF_NAME==system_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_2/system_auto_ds_2_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_3/system_auto_ds_3_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_ds_3 || ORIG_REF_NAME==system_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/ip/system_auto_ds_3/system_auto_ds_3_ooc.xdc

# XDC: /home/grigory/teset/hdl/projects/adv7511/zc702/adv7511_zc702.gen/sources_1/bd/system/system_ooc.xdc
