
# constraints
# hdmi

set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS25} [get_ports hdmi_out_clk]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_vsync]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_hsync]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_data_e]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[0]}]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[1]}]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[2]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[3]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[4]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[5]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[6]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[7]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[8]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[9]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[10]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[11]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[12]}]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[13]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[14]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[15]}]

# spdif

set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS25} [get_ports spdif]

# iic

set_property PACKAGE_PIN W11 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS25 [get_ports iic_scl]
set_property PULLUP true [get_ports iic_scl]
set_property PACKAGE_PIN W8 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS25 [get_ports iic_sda]
set_property PULLUP true [get_ports iic_sda]

# gpio (switches, leds and such)

set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[0]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[1]}]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[2]}]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[3]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[4]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[5]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[6]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[7]}]

# Define SPI clock
create_clock -period 40.000 -name spi0_clk [get_pins -hier */EMIOSPI0SCLKO]
create_clock -period 40.000 -name spi1_clk [get_pins -hier */EMIOSPI1SCLKO]

#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[15]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[18]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[19]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[16]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[17]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[8]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[9]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[10]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[11]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[12]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[26]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[27]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[24]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[25]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[22]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[23]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[20]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[30]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[31]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[28]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[29]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[21]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[13]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_data[14]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_last}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_valid}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[14]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[17]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[18]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[15]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[16]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[13]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[11]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[25]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[26]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[23]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[24]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[21]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[22]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[19]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[31]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[29]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[30]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[27]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[28]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[20]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[12]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[8]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[9]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[10]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_valid}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[17]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[18]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[19]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[20]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[13]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[14]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[15]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[16]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[25]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[26]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[27]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[28]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[21]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[22]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[23]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[24]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[33]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[34]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[35]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[36]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[29]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[30]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[31]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[32]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[37]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[38]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[39]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[8]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[9]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[10]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[11]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[12]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][15]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][16]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][17]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][18]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][11]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][12]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][13]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][14]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][23]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][24]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][25]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][26]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][19]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][20]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][21]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][22]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][31]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][32]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][33]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][34]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][27]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][28]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][29]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][30]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][39]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][35]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][36]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][37]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][38]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][8]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][9]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][10]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_min_max_ready[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_araddr[6]}]
#set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/procedural_1/inst/s_axil_arvalid]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_araddr[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_araddr[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_araddr[5]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_araddr[7]}]
#set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/procedural_1/inst/s_axil_rready]
#set_property MARK_DEBUG true [get_nets i_system_wrapper/system_i/procedural_1/inst/s_axil_rvalid]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[0]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[6]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[9]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[4]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[1]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[2]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[3]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[7]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[14]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[15]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[12]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[13]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[8]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[10]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[11]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[16]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[22]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[23]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[20]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[21]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[17]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[18]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[19]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[24]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[30]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[31]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[28]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[29]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[25]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[26]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[27]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[48]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[53]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[54]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[51]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[52]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[49]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[50]}]
#set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/procedural_1/inst/s_axil_rdata[55]}]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/sys_ps7/inst/FCLK_CLK1]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 5 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/procedural_1/s_axil_araddr[3]} {i_system_wrapper/system_i/procedural_1/s_axil_araddr[4]} {i_system_wrapper/system_i/procedural_1/s_axil_araddr[5]} {i_system_wrapper/system_i/procedural_1/s_axil_araddr[6]} {i_system_wrapper/system_i/procedural_1/s_axil_araddr[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 40 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/procedural_1/s_axil_rdata[0]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[1]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[2]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[3]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[4]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[5]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[6]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[7]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[8]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[9]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[10]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[11]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[12]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[13]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[14]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[15]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[16]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[17]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[18]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[19]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[20]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[21]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[22]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[23]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[24]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[25]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[26]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[27]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[28]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[29]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[30]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[31]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[48]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[49]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[50]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[51]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[52]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[53]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[54]} {i_system_wrapper/system_i/procedural_1/s_axil_rdata[55]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 40 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[0]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[1]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[2]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[3]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[4]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[5]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[6]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[7]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[8]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[9]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[10]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[11]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[12]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[13]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[14]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[15]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[16]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[17]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[18]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[19]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[20]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[21]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[22]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[23]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[24]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[25]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[26]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[27]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[28]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[29]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[30]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[31]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[32]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[33]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[34]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[35]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[36]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[37]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[38]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_data[39]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 8 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[0]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[1]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[2]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[3]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[4]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[5]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[6]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_indx_data[7]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 32 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[0]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[1]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[2]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[3]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[4]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[5]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[6]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[7]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[8]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[9]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[10]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[11]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[12]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[13]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[14]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[15]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[16]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[17]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[18]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[19]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[20]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[21]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[22]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[23]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[24]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[25]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[26]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[27]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[28]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[29]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[30]} {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/o_res_data[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/s_min_max_ready[0]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 40 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][0]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][1]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][2]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][3]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][4]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][5]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][6]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][7]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][8]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][9]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][10]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][11]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][12]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][13]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][14]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][15]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][16]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][17]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][18]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][19]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][20]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][21]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][22]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][23]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][24]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][25]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][26]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][27]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][28]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][29]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][30]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][31]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][32]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][33]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][34]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][35]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][36]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][37]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][38]} {i_system_wrapper/system_i/procedural_1/inst/w_arr_max_min[0][39]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_last}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MIN_MAX/i_valid}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list {i_system_wrapper/system_i/procedural_1/inst/block[0].min_max[0].MEM_MIN_MAX/i_wr_valid}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
#set_property port_width 1 [get_debug_ports u_ila_0/probe10]
#connect_debug_port u_ila_0/probe10 [get_nets [list i_system_wrapper/system_i/procedural_1/s_axil_arvalid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
#set_property port_width 1 [get_debug_ports u_ila_0/probe11]
#connect_debug_port u_ila_0/probe11 [get_nets [list i_system_wrapper/system_i/procedural_1/s_axil_rvalid]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
#set_property port_width 1 [get_debug_ports u_ila_0/probe12]
#connect_debug_port u_ila_0/probe12 [get_nets [list i_system_wrapper/system_i/procedural_1/s_axil_rready]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]

set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/sys_ps7/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][1][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][2][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[0][3][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][1][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][2][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[1][3][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][1][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][2][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[2][3][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][0][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 8 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][1][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][2][7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][0]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][1]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][2]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][3]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][4]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][5]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][6]} {i_system_wrapper/system_i/signal_gen_top_0/inst/u_gen/w_amp_cfg[3][3][7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
